### ISSUE TITLE
Use Delton's workshop scripting language to allow people to contibute code.

### ISSUE THREAD

**Issue by Tensounder54** [lunetoiles/overwatch-race#25]
Could you de-compile the code and/or rewrite it into [ItsDeltin/Overwatch-Script-To-Workshop](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop)? 

Happy to help and answer any questions.

**Comment by lunetoiles** [comment]
Although I honestly should use what the community is using, I've grown really attached to the psuedocode I use. I also think it is good to write in something closer to the in-game language since it makes debugging easier.

That said, I do plan on making a compiler for my own code as well!

**Comment by Tensounder54** [comment]
Please see #28 for added `.oww` code for this game mode.
